### ISSUE TITLE
Why `TechnicalCollective` is not implemented in runtime?

### ISSUE THREAD

**Issue by ayushmishra2005** [sacha-l/substrate-hacking#4]
I was going through this documentaion https://github.com/sacha-l/substrate-hacking/tree/governance-stuff#council. When I checked the codebase, I found that `TechnicalCollective` is not implemented in runtime https://github.com/sacha-l/substrate-hacking/blob/governance-stuff/runtime/src/lib.rs.

Is there any specific reason for that?

**Comment by sacha-l** [comment]
Hi @ayushmishra2005, thanks for reaching out. 

There was no particular reason other than I wanted to simplify things a bit which is why there's only one instance of [`pallet_collective`](https://github.com/sacha-l/substrate-hacking/blob/342bbba85ff5ed20d125901edeec7cdc31b736f8/runtime/src/lib.rs#L452) representing a general council. 

The code snippet in the [README](https://github.com/sacha-l/substrate-hacking/tree/governance-stuff#council) is taken from Polkadot's runtime which does have the `TechnicalCollective` implemented.  I used that to allude to how we can make use of multiple instances of `pallet_collective` to define different collectives. You will find the need to include [`pallet_membership`](https://github.com/paritytech/substrate/tree/master/frame/membership) for cases where you want to enforce special functionalities on a collective, like setting a prime member set for voting &mdash; which is how Polkadot's runtime is built. Take a look at [this example](https://github.com/sacha-l/substrate-hacking/blob/58150fa28ebb0acd2a0befb808d833fec7e14bc0/runtime/src/lib.rs#L295-L324) in the other branch where I use these pallets and concepts in a student government context. Hope this answers your question!

**Comment by ayushmishra2005** [comment]
great thanks @sacha-l
